// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGxZOb7v-tcqblaHpEULHnwtEnJQZ5P4',
    appId: '1:942268318966:web:fa3df30db3809d18a0d8d7',
    messagingSenderId: '942268318966',
    projectId: 'flutterfire-ui-codelab-96d7c',
    authDomain: 'flutterfire-ui-codelab-96d7c.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-96d7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDUnZ837W8xKBiKTuha58SneuYg33_i2A',
    appId: '1:942268318966:android:473c25d56720bf50a0d8d7',
    messagingSenderId: '942268318966',
    projectId: 'flutterfire-ui-codelab-96d7c',
    storageBucket: 'flutterfire-ui-codelab-96d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiFs3kyl8diPR0pmWCqAOOU9xNfTI7wZ8',
    appId: '1:942268318966:ios:948fd24a8017a879a0d8d7',
    messagingSenderId: '942268318966',
    projectId: 'flutterfire-ui-codelab-96d7c',
    storageBucket: 'flutterfire-ui-codelab-96d7c.appspot.com',
    iosClientId: '942268318966-74l0m4p3qk6eghf8iqcukme31jt5gkmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiFs3kyl8diPR0pmWCqAOOU9xNfTI7wZ8',
    appId: '1:942268318966:ios:948fd24a8017a879a0d8d7',
    messagingSenderId: '942268318966',
    projectId: 'flutterfire-ui-codelab-96d7c',
    storageBucket: 'flutterfire-ui-codelab-96d7c.appspot.com',
    iosClientId: '942268318966-74l0m4p3qk6eghf8iqcukme31jt5gkmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
